name: amazon-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - laspy=2.5.4
  - openai=1.82.1
  - python-dotenv=1.1.0
  - rasterio=1.4.3
  - requests=2.32.3
  - matplotlib=3.10.3
  - earthengine-api=1.5.18
  - urllib3=2.4.0
  - pip
  - pip:
    # Add any pip-specific packages here if needed
    # - package_name==version
